services:
  db:
    image: rinha:latest
    build:
      context: .
      dockerfile: database/postgresql.Dockerfile
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: America/Manaus
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    environment:
      TZ: America/Manaus
    ports:
      - 8080:8080

  app:
    image: rinha-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      DB_HOST: db
    depends_on:
      - db
    ports:
      - 8099:8099
