version: "3.5"

services:
  api01: &api
    image: mikaelsouza/rinha-app:latest
    environment:
      DB_HOST: db
      HTTP_PORT: 8080
    deploy:
      resources:
        limits:
          cpus: "0.35"
          memory: "20MB"

  api02:
    <<: *api
 
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
     - "9999:9999"
    depends_on:
      - api01
      - api02
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "100MB"

  db:
    image: mikaelsouza/rinha-db:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: America/Manaus
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "400MB"

  adminer:
    image: adminer
    restart: always
    environment:
      TZ: America/Manaus
    ports:
      - 8080:8080